"""
Django settings for ppg project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path



# プロジェクト内のビルドパスは次のようにします: BASE_DIR / 'subdir'。
# BASE_DIR は、settings.py を基準にしたパス操作のための変数です。
# BASE_DIR / 'templates' や BASE_DIR / 'static' のように使うことで、相対パスでのファイル指定を明確かつ安全にできます。
BASE_DIR = Path(__file__).resolve().parent.parent




# セキュリティ警告: 本番環境ではデバッグをオンにした状態で実行しないでください。
# デバッグモード（開発時はTrue、本番環境では必ずFalse）
DEBUG = True
# DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'



# セキュリティ警告: 本番環境で使用される秘密キーは秘密にしておいてください。
SECRET_KEY = 'django-insecure-w322ce3+jtjib1%$tlr_+kz#a!b3cczj!q4$c8j(m)h7f-w%fn'

# 本番環境では SECRET_KEY を .env に記述し、開発中はベタ書きで対応する構成です。
# if DEBUG:
#     SECRET_KEY = 'django-insecure-w322ce3+jtjib1%$tlr_+kz#a!b3cczj!q4$c8j(m)h7f-w%fn'
# else:
#     SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')




# Djangoでは、本番環境で受け入れるリクエストの「ホスト名（ドメイン/IP）」を明示的に設定する必要があります。
# 未設定のままだと、本番でアクセスした際に DisallowedHost エラーが発生します。
# 開発段階ではワイルドカード ['*'] が使えますが、本番では厳禁です。
ALLOWED_HOSTS = [
    # 'example.com',        # 独自ドメイン
    # 'www.example.com',    # www付きの場合
    # 'xxx.xxx.xxx.xxx',    # Elastic IP
    'localhost',            # ローカル環境の確認用
    '127.0.0.1',            # ローカルIP（ローカルテスト用）
]


# Application definition
# インストール済みアプリケーション
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ppgapp',  # 追加した
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ppg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ppg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# データベース設定（デフォルトはSQLite）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ja'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 静的ファイルのURL
STATIC_URL = 'static/'
# プロジェクト共通の静的ファイルを置きたい場合のみ以下を追加
# STATICFILES_DIRS = [BASE_DIR / "static"]
